export interface StakeWizValidator {
  rank: number;
  identity: string;
  vote_identity: string;
  last_vote: number;
  root_slot: number;
  credits: number;
  epoch_credits: number;
  activated_stake: number;
  version: string;
  delinquent: boolean;
  skip_rate: number;
  wiz_skip_rate?: number;
  updated_at: string;
  first_epoch_with_stake?: number;
  name?: string;
  keybase?: string;
  description?: string;
  website?: string;
  commission: number;
  image?: string;
  ip_latitude?: string;
  ip_longitude?: string;
  ip_city?: string;
  ip_country?: string;
  ip_asn?: string;
  ip_org?: string;
  is_jito?: boolean;
  jito_commission_bps?: number;
  vote_success?: number;
  uptime?: number;
  epoch?: number;
  apy_estimate?: number;
  staking_apy?: number;
  jito_apy?: number;
  total_apy?: number;
}

export interface ValidatorInfo {
  address: string;
  votingPubkey: string;
  name: string;
  commission: number;
  stake: number;
  delegatedStake: number;
  activatedStake: number;
  apy: number;
  skipRate: number;
  dataCenter: string;
  website?: string;
  description: string;
  avatar: string;
  status: "active" | "delinquent";
  epochCredits: number[];
  lastVote: number;
  rootSlot: number;
  country?: string;
  city?: string;
  uptime?: number;
  performanceHistory: any[];
  location?: {
    coordinates: [number, number];
    city?: string;
    country?: string;
    countryCode?: string;
    latitude: number;
    longitude: number;
    lat: number;
    lng: number;
  };
  identity: string;
  voteIdentity: string;
  rank: number;
  version: string;
  isJito?: boolean;
  asn?: string;
  asnOrganization?: string;
  totalApy?: number;
  stakingApy?: number;
  jitoApy?: number;
}
